name: idea_widget_preview
description: Widget Preview in IDEA-based development environments.
version: 0.0.5
homepage: https://github.com/andrasferenczi/idea_widget_preview

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  analyzer: ^5.13.0
  collection: ^1.17.1
  device_frame: ^1.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  http: ^1.1.0
  intl: ^0.18.0
  meta: ^1.9.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  dart_style: ^2.3.2
  lints: ^2.1.1
  test: ^1.24.4

flutter:
  uses-material-design: true
